// LinkedIn OAuth — Step 2: exchange code, fetch user's admin'd Company Pages,
// and persist tokens scoped to the organization that initiated the flow.
//
// Public endpoint (no JWT). Security comes from the HMAC-signed `state`
// parameter generated by linkedin-oauth-start.
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.58.0";

async function verifyState(
  state: string,
  secret: string,
): Promise<Record<string, any> | null> {
  try {
    const [body, sigB64] = state.split(".");
    if (!body || !sigB64) return null;
    const key = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(secret),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["verify"],
    );
    const sig = Uint8Array.from(atob(sigB64), (c) => c.charCodeAt(0));
    const ok = await crypto.subtle.verify(
      "HMAC",
      key,
      sig,
      new TextEncoder().encode(body),
    );
    if (!ok) return null;
    const payload = JSON.parse(atob(body));
    if (typeof payload.exp !== "number" || payload.exp < Date.now()) return null;
    return payload;
  } catch {
    return null;
  }
}

function redirect(url: string): Response {
  return new Response(null, {
    status: 302,
    headers: { Location: url },
  });
}

function pickFrontendOrigin(req: Request): string {
  const ref = req.headers.get("referer");
  if (ref) {
    try {
      const u = new URL(ref);
      if (!u.hostname.endsWith("linkedin.com")) return u.origin;
    } catch { /* ignore */ }
  }
  const fromEnv = Deno.env.get("FRONTEND_URL");
  if (fromEnv) return fromEnv.replace(/\/$/, "");
  return "https://impact-ignite-suite.lovable.app";
}

serve(async (req) => {
  const url = new URL(req.url);
  const code = url.searchParams.get("code");
  const stateRaw = url.searchParams.get("state");
  const liError = url.searchParams.get("error");
  const liErrorDescription = url.searchParams.get("error_description");

  const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
  const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const LINKEDIN_CLIENT_ID = Deno.env.get("LINKEDIN_CLIENT_ID");
  const LINKEDIN_CLIENT_SECRET = Deno.env.get("LINKEDIN_CLIENT_SECRET");

  const frontendOrigin = pickFrontendOrigin(req);
  const errorRedirect = (reason: string) =>
    redirect(
      `${frontendOrigin}/dashboard/social?li=error&reason=${encodeURIComponent(reason)}`,
    );

  if (liError) {
    console.warn("[linkedin-oauth-callback] LinkedIn returned error", {
      liError,
      liErrorDescription,
    });
    return errorRedirect(liErrorDescription || liError);
  }

  if (!code || !stateRaw) {
    return errorRedirect("Missing code or state");
  }

  if (!LINKEDIN_CLIENT_ID || !LINKEDIN_CLIENT_SECRET) {
    return errorRedirect(
      "LinkedIn integration not yet configured by platform admin",
    );
  }

  const state = await verifyState(stateRaw, SERVICE_KEY);
  if (!state) {
    return errorRedirect("Invalid or expired authorization state");
  }
  const orgId = state.org_id as string;
  const userId = state.user_id as string;
  const returnTo = (state.return_to as string) || "/dashboard/social";

  const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
    auth: { persistSession: false },
  });

  try {
    const redirectUri = `${SUPABASE_URL}/functions/v1/linkedin-oauth-callback`;

    // 1. Exchange auth code → access token
    const tokenRes = await fetch(
      "https://www.linkedin.com/oauth/v2/accessToken",
      {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: new URLSearchParams({
          grant_type: "authorization_code",
          code,
          redirect_uri: redirectUri,
          client_id: LINKEDIN_CLIENT_ID,
          client_secret: LINKEDIN_CLIENT_SECRET,
        }),
      },
    );
    const tokenJson = await tokenRes.json();
    if (!tokenRes.ok || !tokenJson.access_token) {
      console.error("[linkedin-oauth-callback] token exchange failed", tokenJson);
      return errorRedirect(
        tokenJson?.error_description || tokenJson?.error || "Failed to exchange authorization code",
      );
    }

    const accessToken: string = tokenJson.access_token;
    const expiresIn: number | null = typeof tokenJson.expires_in === "number"
      ? tokenJson.expires_in
      : null;
    const expiresAt = expiresIn
      ? new Date(Date.now() + expiresIn * 1000).toISOString()
      : null;

    // 2. Identify the connecting user (via OpenID userinfo)
    const meRes = await fetch("https://api.linkedin.com/v2/userinfo", {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    const meJson = await meRes.json();
    const personSub: string | null = meRes.ok ? meJson?.sub ?? null : null;
    const personName: string | null = meRes.ok
      ? meJson?.name ?? `${meJson?.given_name ?? ""} ${meJson?.family_name ?? ""}`.trim() ?? null
      : null;
    const personUrn = personSub ? `urn:li:person:${personSub}` : null;

    // 3. Fetch Organizations the user can administer (Company Pages)
    // organizationAcls returns ACL entries; we need ones with role ADMINISTRATOR/DIRECT_SPONSORED_CONTENT_POSTER
    // and state APPROVED. We then resolve each organization's name + logo.
    type Page = {
      org_id: string;          // numeric
      org_urn: string;         // urn:li:organization:{id}
      name: string;
      vanity_name: string | null;
      logo_url: string | null;
      role: string;
    };
    const pages: Page[] = [];

    try {
      const aclUrl = new URL("https://api.linkedin.com/v2/organizationAcls");
      aclUrl.searchParams.set("q", "roleAssignee");
      aclUrl.searchParams.set(
        "role",
        "ADMINISTRATOR",
      );
      aclUrl.searchParams.set("state", "APPROVED");
      aclUrl.searchParams.set("count", "50");

      const aclRes = await fetch(aclUrl.toString(), {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "X-Restli-Protocol-Version": "2.0.0",
        },
      });
      const aclJson = await aclRes.json();

      if (aclRes.ok && Array.isArray(aclJson?.elements)) {
        for (const el of aclJson.elements) {
          const orgUrn: string | undefined = el.organization;
          if (!orgUrn) continue;
          const numericId = orgUrn.split(":").pop()!;

          // Resolve org details
          let name = `Organization ${numericId}`;
          let vanity: string | null = null;
          let logoUrl: string | null = null;
          try {
            const orgRes = await fetch(
              `https://api.linkedin.com/v2/organizations/${numericId}?projection=(id,localizedName,vanityName,logoV2(original~:playableStreams))`,
              {
                headers: {
                  Authorization: `Bearer ${accessToken}`,
                  "X-Restli-Protocol-Version": "2.0.0",
                },
              },
            );
            const orgJson = await orgRes.json();
            if (orgRes.ok) {
              name = orgJson?.localizedName ?? name;
              vanity = orgJson?.vanityName ?? null;
              const elements =
                orgJson?.logoV2?.["original~"]?.elements ?? [];
              const first = elements[0]?.identifiers?.[0]?.identifier;
              if (typeof first === "string") logoUrl = first;
            }
          } catch (e) {
            console.warn("[linkedin-oauth-callback] org details fetch failed", numericId, e);
          }

          pages.push({
            org_id: numericId,
            org_urn: orgUrn,
            name,
            vanity_name: vanity,
            logo_url: logoUrl,
            role: el.role ?? "ADMINISTRATOR",
          });
        }
      } else {
        console.warn("[linkedin-oauth-callback] organizationAcls failed", aclJson);
      }
    } catch (e) {
      console.warn("[linkedin-oauth-callback] organizationAcls request error", e);
    }

    if (pages.length === 0) {
      return errorRedirect(
        "Connected to LinkedIn but found no Company Pages you administer. Make sure your LinkedIn account is an admin of the Page, and that your LinkedIn App has been approved for the Marketing Developer Platform.",
      );
    }

    // 4. Upsert one integration row per Page
    let upserted = 0;
    for (const page of pages) {
      const config = {
        page_id: page.org_id,
        page_urn: page.org_urn,
        page_name: page.name,
        account_name: page.name,
        vanity_name: page.vanity_name,
        picture_url: page.logo_url,
        role: page.role,
        connected_user_id: userId,
        connected_user_urn: personUrn,
        connected_user_name: personName,
        connected_at: new Date().toISOString(),
      };
      const tokens = {
        access_token: accessToken,
        token_expires_at: expiresAt,
      };

      const { data: existing } = await supabase
        .from("integrations")
        .select("id")
        .eq("organization_id", orgId)
        .eq("provider", "linkedin")
        .contains("config", { page_id: page.org_id })
        .maybeSingle();

      if (existing?.id) {
        const { error: upErr } = await supabase
          .from("integrations")
          .update({
            status: "active",
            config,
            encrypted_tokens: tokens,
            last_synced_at: new Date().toISOString(),
            name: `LinkedIn — ${page.name}`,
          })
          .eq("id", existing.id);
        if (upErr) console.error("[linkedin-oauth-callback] update error", upErr);
        else upserted++;
      } else {
        const { error: insErr } = await supabase
          .from("integrations")
          .insert({
            organization_id: orgId,
            provider: "linkedin",
            name: `LinkedIn — ${page.name}`,
            status: "active",
            config,
            encrypted_tokens: tokens,
            last_synced_at: new Date().toISOString(),
          });
        if (insErr) console.error("[linkedin-oauth-callback] insert error", insErr);
        else upserted++;
      }
    }

    if (upserted === 0) {
      return errorRedirect(
        "Connected to LinkedIn but failed to save Page details. Try again or contact support.",
      );
    }

    return redirect(
      `${frontendOrigin}${returnTo}?li=connected&pages=${upserted}`,
    );
  } catch (error: any) {
    console.error("[linkedin-oauth-callback] unexpected error", error);
    return errorRedirect(error?.message ?? "Unexpected error during connection");
  }
});
