// Facebook OAuth — Step 2: exchange code, fetch user's Pages, persist tokens
// scoped to the organization that initiated the flow.
//
// This endpoint is called by Facebook in the user's browser. It is NOT
// authenticated via JWT — the security comes from the HMAC-signed `state`
// parameter generated by facebook-oauth-start.
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.58.0";

const FB_API_VERSION = "v19.0";

async function verifyState(
  state: string,
  secret: string,
): Promise<Record<string, any> | null> {
  try {
    const [body, sigB64] = state.split(".");
    if (!body || !sigB64) return null;
    const key = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(secret),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["verify"],
    );
    const sig = Uint8Array.from(atob(sigB64), (c) => c.charCodeAt(0));
    const ok = await crypto.subtle.verify(
      "HMAC",
      key,
      sig,
      new TextEncoder().encode(body),
    );
    if (!ok) return null;
    const payload = JSON.parse(atob(body));
    if (typeof payload.exp !== "number" || payload.exp < Date.now()) return null;
    return payload;
  } catch {
    return null;
  }
}

function redirect(url: string): Response {
  return new Response(null, {
    status: 302,
    headers: { Location: url },
  });
}

function pickFrontendOrigin(req: Request): string {
  // Try the Referer first (set by FB when bouncing the user)
  const ref = req.headers.get("referer");
  if (ref) {
    try {
      const u = new URL(ref);
      // Don't bounce back to facebook.com — fall back to env
      if (!u.hostname.endsWith("facebook.com")) return u.origin;
    } catch { /* ignore */ }
  }
  // Allow platform admin to set a canonical frontend URL
  const fromEnv = Deno.env.get("FRONTEND_URL");
  if (fromEnv) return fromEnv.replace(/\/$/, "");
  // Last resort — published Lovable URL pattern
  return "https://impact-ignite-suite.lovable.app";
}

serve(async (req) => {
  const url = new URL(req.url);
  const code = url.searchParams.get("code");
  const stateRaw = url.searchParams.get("state");
  const fbError = url.searchParams.get("error");
  const fbErrorReason = url.searchParams.get("error_reason");
  const fbErrorDescription = url.searchParams.get("error_description");

  const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
  const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const FACEBOOK_APP_ID = Deno.env.get("FACEBOOK_APP_ID");
  const FACEBOOK_APP_SECRET = Deno.env.get("FACEBOOK_APP_SECRET");

  const frontendOrigin = pickFrontendOrigin(req);
  const errorRedirect = (reason: string) =>
    redirect(
      `${frontendOrigin}/dashboard/social?fb=error&reason=${encodeURIComponent(reason)}`,
    );

  if (fbError) {
    console.warn("[facebook-oauth-callback] FB returned error", {
      fbError,
      fbErrorReason,
      fbErrorDescription,
    });
    return errorRedirect(fbErrorDescription || fbErrorReason || fbError);
  }

  if (!code || !stateRaw) {
    return errorRedirect("Missing code or state");
  }

  if (!FACEBOOK_APP_ID || !FACEBOOK_APP_SECRET) {
    return errorRedirect(
      "Facebook integration not yet configured by platform admin",
    );
  }

  const state = await verifyState(stateRaw, SERVICE_KEY);
  if (!state) {
    return errorRedirect("Invalid or expired authorization state");
  }
  const orgId = state.org_id as string;
  const userId = state.user_id as string;
  const returnTo = (state.return_to as string) || "/dashboard/social";

  const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
    auth: { persistSession: false },
  });

  try {
    const redirectUri = `${SUPABASE_URL}/functions/v1/facebook-oauth-callback`;

    // 1. Exchange auth code for short-lived user token
    const tokenUrl = new URL(
      `https://graph.facebook.com/${FB_API_VERSION}/oauth/access_token`,
    );
    tokenUrl.searchParams.set("client_id", FACEBOOK_APP_ID);
    tokenUrl.searchParams.set("client_secret", FACEBOOK_APP_SECRET);
    tokenUrl.searchParams.set("redirect_uri", redirectUri);
    tokenUrl.searchParams.set("code", code);

    const shortRes = await fetch(tokenUrl.toString());
    const shortJson = await shortRes.json();
    if (!shortRes.ok || !shortJson.access_token) {
      console.error("[facebook-oauth-callback] short-lived exchange failed", shortJson);
      return errorRedirect(
        shortJson?.error?.message || "Failed to exchange authorization code",
      );
    }

    // 2. Exchange short-lived → long-lived (~60 day) user token
    const longUrl = new URL(
      `https://graph.facebook.com/${FB_API_VERSION}/oauth/access_token`,
    );
    longUrl.searchParams.set("grant_type", "fb_exchange_token");
    longUrl.searchParams.set("client_id", FACEBOOK_APP_ID);
    longUrl.searchParams.set("client_secret", FACEBOOK_APP_SECRET);
    longUrl.searchParams.set("fb_exchange_token", shortJson.access_token);

    const longRes = await fetch(longUrl.toString());
    const longJson = await longRes.json();
    if (!longRes.ok || !longJson.access_token) {
      console.error("[facebook-oauth-callback] long-lived exchange failed", longJson);
      return errorRedirect(
        longJson?.error?.message || "Failed to obtain long-lived user token",
      );
    }

    const userAccessToken: string = longJson.access_token;
    const userTokenExpiresIn: number | null = typeof longJson.expires_in === "number"
      ? longJson.expires_in
      : null;
    const userTokenExpiresAt = userTokenExpiresIn
      ? new Date(Date.now() + userTokenExpiresIn * 1000).toISOString()
      : null;

    // 3. Fetch the user's Pages with their per-Page access tokens
    const pagesUrl = new URL(
      `https://graph.facebook.com/${FB_API_VERSION}/me/accounts`,
    );
    pagesUrl.searchParams.set(
      "fields",
      "id,name,access_token,category,picture{url},tasks",
    );
    pagesUrl.searchParams.set("access_token", userAccessToken);

    const pagesRes = await fetch(pagesUrl.toString());
    const pagesJson = await pagesRes.json();
    if (!pagesRes.ok) {
      console.error("[facebook-oauth-callback] /me/accounts failed", pagesJson);
      return errorRedirect(
        pagesJson?.error?.message || "Failed to fetch your Facebook Pages",
      );
    }

    const pages: Array<any> = pagesJson.data ?? [];
    if (pages.length === 0) {
      return errorRedirect(
        "No Facebook Pages found on this account. You must be an admin of at least one Page.",
      );
    }

    // 4. Upsert one integration row per Page
    let upserted = 0;
    for (const page of pages) {
      // Only keep Pages where this user can actually create content
      const canPost = !page.tasks ||
        (Array.isArray(page.tasks) && page.tasks.some((t: string) =>
          ["CREATE_CONTENT", "MANAGE", "MODERATE"].includes(t)
        ));
      if (!canPost) continue;

      const config = {
        page_id: page.id,
        page_name: page.name,
        account_name: page.name,
        category: page.category ?? null,
        picture_url: page.picture?.data?.url ?? null,
        connected_user_id: userId,
        connected_at: new Date().toISOString(),
      };
      const tokens = {
        page_access_token: page.access_token,
        user_access_token: userAccessToken,
        user_token_expires_at: userTokenExpiresAt,
      };

      // Look for an existing integration for this org+page
      const { data: existing } = await supabase
        .from("integrations")
        .select("id")
        .eq("organization_id", orgId)
        .eq("provider", "facebook")
        .contains("config", { page_id: page.id })
        .maybeSingle();

      if (existing?.id) {
        const { error: upErr } = await supabase
          .from("integrations")
          .update({
            status: "active",
            config,
            encrypted_tokens: tokens,
            last_synced_at: new Date().toISOString(),
            name: `Facebook — ${page.name}`,
          })
          .eq("id", existing.id);
        if (upErr) console.error("[facebook-oauth-callback] update error", upErr);
        else upserted++;
      } else {
        const { error: insErr } = await supabase
          .from("integrations")
          .insert({
            organization_id: orgId,
            provider: "facebook",
            name: `Facebook — ${page.name}`,
            status: "active",
            config,
            encrypted_tokens: tokens,
            last_synced_at: new Date().toISOString(),
          });
        if (insErr) console.error("[facebook-oauth-callback] insert error", insErr);
        else upserted++;
      }
    }

    if (upserted === 0) {
      return errorRedirect(
        "Connected to Facebook but found no Pages where you can publish posts.",
      );
    }

    return redirect(
      `${frontendOrigin}${returnTo}?fb=connected&pages=${upserted}`,
    );
  } catch (error: any) {
    console.error("[facebook-oauth-callback] unexpected error", error);
    return errorRedirect(error?.message ?? "Unexpected error during connection");
  }
});
