// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svuxuhrsrawdqqkepeye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dXh1aHJzcmF3ZHFxa2VwZXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTgxMzIsImV4cCI6MjA3NDQ3NDEzMn0.4qw467jq5sB3JAGPXgCnUopFvBVWDUR5FN2Lz3c_RQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});